trigger:
- master

variables:
  azureServiceConnectionId: '35154707-5f47-4d56-9fdd-3b74a6f9740a'
  webAppName: 'SimpleFlaskApp'
  environmentName: 'SimpleFlaskApp'
  projectRoot: $(System.DefaultWorkingDirectory)
  pythonVersion: '3.11'

stages:
- stage: Build
  displayName: 'Build Stage'
  jobs:
  - job: BuildJob
    pool:
      name: default
      demands:
      - Agent.Name -equals DESKTOP-S8V1BUP
    steps:
    - script: |
        python -m venv antenv
        source antenv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt
      workingDirectory: $(projectRoot)
      displayName: "Install Python Dependencies"

    - task: ArchiveFiles@2
      displayName: 'Archive App Files'
      inputs:
        rootFolderOrFile: '$(projectRoot)'
        includeRootFolder: false
        archiveType: zip
        archiveFile: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
        replaceExistingArchive: true

    - publish: '$(Build.ArtifactStagingDirectory)/$(Build.BuildId).zip'
      artifact: drop

- stage: Deploy
  displayName: 'Deploy to Azure Web App'
  dependsOn: Build
  condition: succeeded()
  jobs:
  - deployment: DeployJob
    environment: $(environmentName)
    pool:
      name: default
      demands:
      - Agent.Name -equals DESKTOP-S8V1BUP
    strategy:
      runOnce:
        deploy:
          steps:
          - task: AzureWebApp@1
            displayName: 'Deploy Flask App to Azure Web App'
            inputs:
              azureSubscription: $(azureServiceConnectionId)
              appName: $(webAppName)
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip'
